import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { nomSecretHotel, validerSessionHotel } from "../_shared/hotel-session.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const ORIGINS = new Set(["https://elatransfer.com", "https://www.elatransfer.com"]);
const MAX_BODY = 24_000;

/* LE N° COURT (5 octobre 2026) : attribué par la base à l'écriture de la
   ligne et recopié dans le bon ; relu ici pour que le client l'ait sur son
   bon. Avant la migration il n'existe pas : rien n'est rendu. Un échec ne
   coûte RIEN — la demande est déjà enregistrée, le client garde sa référence. */
function numeroDe(l:any):Record<string,number>{const n=Number(l&&l.bon&&l.bon.numero);return n>0?{numero:n}:{}}
async function lireNumero(ref:string):Promise<Record<string,number>>{try{const r=await fetch(`${SUPABASE_URL}/rest/v1/courses?ref=eq.${encodeURIComponent(ref)}&select=bon&limit=1`,{headers:{apikey:SERVICE_ROLE,Authorization:`Bearer ${SERVICE_ROLE}`}});if(!r.ok)return {};const l=await r.json();return numeroDe(Array.isArray(l)?l[0]:null)}catch(_e){return {}}}
function reponse(status:number, body:Record<string,unknown>, origin="") { const headers:Record<string,string>={"Content-Type":"application/json","Cache-Control":"no-store","Vary":"Origin"}; if(ORIGINS.has(origin))headers["Access-Control-Allow-Origin"]=origin; return new Response(JSON.stringify(body),{status,headers}); }
function texte(v:unknown,max:number){return typeof v==="string"?v.trim().slice(0,max):""}
function nombre(v:unknown,min:number,max:number){const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:null}
function booleen(v:unknown){return v===true}
function entierPassagers(v:unknown){if(typeof v==="number")return nombre(v,1,60);if(typeof v!=="string")return null;const m=v.match(/^\s*(\d+)/);return m?nombre(m[1],1,60):null}
function entierBagages(v:unknown){if(typeof v==="number")return nombre(v,0,60);if(typeof v!=="string")return 0;const m=v.match(/(?:·|\s)(\d+)\s+bagage/i);return m?nombre(m[1],0,60):0}
async function sha256(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("")}
async function apiJson(path:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SERVICE_ROLE,Authorization:`Bearer ${SERVICE_ROLE}`}});if(!r.ok)throw new Error(`db_${r.status}`);return r.json()}
/* ═══ LE LIEU STRUCTURÉ (4 octobre 2026) ═══ Le site envoie, pour chaque bout du trajet, le lieu CHOISI : nom, adresse, coordonnées, source. Avant, ce serveur jetait même « departPos » : en base, une course n'était que du texte. On garde l'objet, borné et typé — des coordonnées hors du globe ou une chaîne de dix mille caractères ne passent pas. Facultatif : une page plus ancienne, gardée en mémoire sur un téléphone, n'en envoie pas, et sa demande doit passer comme avant. */
const PROVIDERS=new Set(["ban","photon","elatransfer","mapbox"]),SOURCES_ITI=new Set(["mapbox","ors","osrm","vol"]);
/* ═══ PAR OÙ JOINDRE LE CLIENT (4 octobre 2026) ═══ Le site dit où le client veut recevoir sa confirmation (« prefere » : appel/SMS, WhatsApp, Telegram, iMessage) ; « envoi » vaut « site ». Sans cette ligne, le serveur jetait le champ et l'admin ne le voyait jamais. Deux listes fermées : rien d'autre ne passe. */
const ENVOIS=new Set(["whatsapp","telegram","messages","site"]),CANAUX=new Set(["telephone","whatsapp","telegram","messages"]);
function contactPropre(v:any){if(!v||typeof v!=="object"||Array.isArray(v))return null;const envoi=texte(v.envoi,12),prefere=texte(v.prefere,12);if(!ENVOIS.has(envoi))return null;return{envoi,prefere:CANAUX.has(prefere)?prefere:""}}
function lieuPropre(v:any){if(!v||typeof v!=="object"||Array.isArray(v))return null;const lat=nombre(v.latitude,-90,90),lon=nombre(v.longitude,-180,180);if(lat===null||lon===null)return null;const prov=texte(v.provider,20);return{nom:texte(v.nom,160),adresse:texte(v.adresse,300),latitude:lat,longitude:lon,provider:PROVIDERS.has(prov)?prov:"inconnu",providerId:texte(v.providerId,120),categorie:texte(v.categorie,24)}}
function ligneDroiteKm(a:any,b:any){const r=(d:number)=>d*Math.PI/180,dLat=r(b.latitude-a.latitude),dLon=r(b.longitude-a.longitude),h=Math.sin(dLat/2)**2+Math.cos(r(a.latitude))*Math.cos(r(b.latitude))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
/* ═══ LE PRIX AU KILOMÈTRE N'ÉTAIT CONTRÔLÉ PAR PERSONNE ICI (4 octobre 2026) ═══ N'importe qui pouvait déposer « Paris → Roissy, 5 € » depuis la console de son navigateur. Recalculer l'itinéraire ici coûterait un appel et une seconde à chaque réservation, et surtout donnerait un SECOND calcul, avec une autre distance que celle annoncée au client — le prix ferme deviendrait contestable. Le contrôle retenu est gratuit et sans appel extérieur : AUCUNE ROUTE N'EST PLUS COURTE QUE LA LIGNE DROITE. Le minimum possible est donc la ligne droite × le tarif du serveur, arrondi à la dizaine INFÉRIEURE (on ne reprend pas l'arrondi de Barbaros : un plancher plus bas que lui ne se trompe jamais), relevé au montant minimum. Un prix en dessous est SIGNALÉ sur le bon, jamais refusé : si Barbaros augmente un tarif, un téléphone qui garde l'ancienne page annonce honnêtement moins — on ne perd pas ce client. Ce contrôle ne prouve pas que les coordonnées sont vraies ; il arrête la fraude naïve et le tarif périmé. Un forfait partenaire n'est pas concerné : il a son propre contrôle, et un prix d'appel sous le kilométrage y est voulu. */
async function controlerPrixKm(propre:any){const c=propre.course,a=c.departLieu,b=c.arriveeLieu;if(!a||!b||c.destinationCle)return;try{const rows=await apiJson(`parametres_commerciaux?cle=eq.tarif_general_${encodeURIComponent(c.vehiculeCle)}&actif=eq.true&select=valeur&limit=1`),v=rows?.[0]?.valeur,parKm=Number(v?.par_km_centimes)/100,mini=Number(v?.minimum_centimes)/100;if(!(parKm>0)||!(mini>=0))return;const km=ligneDroiteKm(a,b),minimum=Math.max(Math.floor(parKm*km/10)*10,mini);if(propre.prix.total+0.005<minimum)propre.securite.prixSousLigneDroite={minimum,ligneDroiteKm:Math.round(km*10)/10}}catch(e){console.warn("contrôle du prix au kilomètre sauté",String(e))}}
function destinationValide(validation:any,course:any){if(!validation||validation.verification_manuelle)return false;const terminal=texte(course.terminal,80).toLowerCase(),trajet=(texte(course.departPublic||course.depart,300)+" "+texte(course.arriveePublic||course.arrivee,300)).toLowerCase();if(validation.terminal_prefix)return terminal.startsWith(String(validation.terminal_prefix).toLowerCase());if(validation.texte_contient)return trajet.includes(String(validation.texte_contient).toLowerCase());return false}
async function snapshotPartenaire(propre:any){const partenaireCle=texte(propre.provenanceCle,80),destinationCle=texte(propre.course?.destinationCle,40).toLowerCase(),vehiculeCle=texte(propre.course?.vehiculeCle,24).toLowerCase();if(!partenaireCle||!destinationCle||!vehiculeCle)return null;try{const partenaires=await apiJson(`partenaires?cle=eq.${encodeURIComponent(partenaireCle)}&actif=eq.true&select=id&limit=1`);if(!partenaires?.[0]?.id)return null;const tarifs=await apiJson(`tarifs_partenaires?partenaire_id=eq.${encodeURIComponent(partenaires[0].id)}&destination_cle=eq.${encodeURIComponent(destinationCle)}&vehicule_cle=eq.${encodeURIComponent(vehiculeCle)}&actif=eq.true&select=montant_centimes,validation&limit=1`),tarif=tarifs?.[0];if(!tarif||!destinationValide(tarif.validation,propre.course))return null;const params=await apiJson('parametres_commerciaux?cle=eq.commission_ela_defaut&select=valeur&limit=1'),pct=Number(params?.[0]?.valeur?.pourcentage),prix=Number(tarif.montant_centimes);if(!Number.isFinite(pct)||pct<0||pct>100||!Number.isInteger(prix)||prix<50)return null;const chauffeur=Math.round(prix*(1-pct/100));propre.prix={...propre.prix,total:prix/100,ht:Math.round(((prix/100)/1.10)*100)/100,tva:Math.round(((prix/100)-(prix/100)/1.10)*100)/100,serveurVerifie:true};propre.securite={...propre.securite,prixServeurVerifie:true,provenanceServeurVerifie:true,sourceTarif:"partenaire"};return{prix_final_centimes:prix,montant_chauffeur_centimes:chauffeur,marge_ela_centimes:prix-chauffeur,destination_cle:destinationCle}}catch(e){console.warn("tarification partenaire non verrouillée",String(e));return null}}

Deno.serve(async(req:Request)=>{
 const origin=req.headers.get("origin")??"";
 if(req.method==="OPTIONS"){if(!ORIGINS.has(origin))return reponse(403,{erreur:"refusé"});return new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":origin,"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"content-type, apikey","Access-Control-Max-Age":"600","Vary":"Origin"}})}
 if(req.method!=="POST")return reponse(405,{erreur:"méthode refusée"},origin);if(!ORIGINS.has(origin))return reponse(403,{erreur:"origine refusée"});if(!SUPABASE_URL||!SERVICE_ROLE)return reponse(503,{erreur:"service indisponible"},origin);
 const len=Number(req.headers.get("content-length")||0);if(len>MAX_BODY)return reponse(413,{erreur:"requête trop grande"},origin);let brut:string;try{brut=await req.text()}catch{return reponse(400,{erreur:"requête illisible"},origin)}if(brut.length>MAX_BODY)return reponse(413,{erreur:"requête trop grande"},origin);let entree:any;try{entree=JSON.parse(brut)}catch{return reponse(400,{erreur:"requête invalide"},origin)}
 const bon=entree?.bon;if(!bon||typeof bon!=="object"||Array.isArray(bon))return reponse(400,{erreur:"demande invalide"},origin);const ref=texte(bon.ref,32),c=bon.course,client=bon.client,p=bon.prix;if(!/^ELA-[A-Z0-9-]{6,24}$/.test(ref)||!c||typeof c!=="object"||!client||typeof client!=="object"||!p||typeof p!=="object")return reponse(400,{erreur:"demande invalide"},origin);
 /* ═══ UNE COURSE DE DÉMONSTRATION N'EST JAMAIS ENREGISTRÉE (8 octobre 2026, démo professionnels) ═══ La page /demo/hotel/ montre le parcours d'une réception ; un prospect qui pousse jusqu'au bout ne doit pas faire partir une vraie demande, ni sonner Barbaros à 3 h du matin pour une course qui n'existe pas. Toute provenance ou clé partenaire qui commence par « demo » (accents et casse ignorés : « Démo », « DEMO-hotel ») est refusée AVANT le quota et avant toute lecture en base. La page de démo ne doit pas compter sur ce refus pour se taire : c'est la seconde défense. */
 const commenceParDemo=(v:unknown)=>typeof v==="string"&&v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().startsWith("demo");
 if(commenceParDemo(bon.provenance)||commenceParDemo(bon.provenanceCle))return reponse(403,{erreur:"démonstration : aucune course n'est enregistrée"},origin);
 const provenanceCle=texte(bon.provenanceCle,80);let receptionAutorisee=false;
 if(booleen(bon.parReception)){
  const secret=/^[a-z0-9-]{3,40}$/.test(provenanceCle)?Deno.env.get(nomSecretHotel(provenanceCle))??"":"";
  receptionAutorisee=await validerSessionHotel(texte(entree.sessionReception,1500),provenanceCle,secret);
  if(!receptionAutorisee)return reponse(401,{erreur:"session réception refusée"},origin);
 }
 const depart=texte(c.depart,300),arrivee=texte(c.arrivee,300),date=texte(c.date,10),heure=texte(c.heure,5),nom=texte(client.nom,120),tel=texte(client.telephone,40),vehicule=texte(c.vehicule,40),vehiculeCle=texte(c.vehiculeCle,24),paiement=texte(bon.paiement,20),destinationCle=texte(c.destinationCle,40),total=nombre(p.total,0,5000),distanceKm=nombre(c.distanceKm,0,5000),passagers=entierPassagers(c.passagers),bagages=entierBagages(c.passagers);
 // Au comptoir d'un hôtel, la chambre identifie le client : le site accepte « chambre, OU nom et téléphone ». Exiger ici nom et téléphone refusait toute demande faite par la chambre seule (24/09/2026, vu par Barbaros).
 const parChambre=receptionAutorisee&&!!texte(c.chambre,30)&&!!provenanceCle;
 /* « TARIF À CONFIRMER » (4 octobre 2026) : longue distance, groupe, adresse
    tapée à la main. Le prix est alors FORCÉ À ZÉRO — un client ne peut pas y
    glisser un montant — et Elatransfer le fixe dans l'admin. Sinon un prix
    POSITIF est exigé : un 0 € n'était refusé par personne. */
 const MOTIFS=new Set(["longue","groupe","adresse"]),motifs=(Array.isArray(c.motifsTarif)?c.motifsTarif:[]).map((m:unknown)=>texte(m,12)).filter((m:string)=>MOTIFS.has(m)).slice(0,3),aConfirmer=booleen(c.tarifAConfirmer)&&motifs.length>0,prixDepose=aConfirmer?0:(total??0);
 if(!aConfirmer&&!(prixDepose>0))return reponse(400,{erreur:"demande invalide"},origin);
 if(!depart||!arrivee||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(heure)||(!parChambre&&(!nom||tel.length<6))||(tel&&tel.length<6)||!vehicule||!["berline","van"].includes(vehiculeCle)||!["carte","especes"].includes(paiement)||total===null||distanceKm===null||passagers===null||bagages===null)return reponse(400,{erreur:"demande invalide"},origin);
 const propre:any={ref,statut:"attente",course:{type:texte(c.type,40)||"Trajet simple",depart,arrivee,departPublic:texte(c.departPublic,300)||depart,arriveePublic:texte(c.arriveePublic,300)||arrivee,date,heure,terminal:texte(c.terminal,40)||null,vol:texte(c.vol,30),train:texte(c.train,30),note:texte(c.note,200),chambre:texte(c.chambre,30),pancarte:booleen(c.pancarte),vehicule,vehiculeCle,passagers:texte(c.passagers,80),passagersNombre:passagers,bagagesNombre:bagages,distanceKm,destinationCle,estimee:booleen(c.estimee),departLieu:lieuPropre(c.departLieu),arriveeLieu:lieuPropre(c.arriveeLieu),itineraireSource:SOURCES_ITI.has(texte(c.itineraireSource,10))?texte(c.itineraireSource,10):"",immediat:booleen(c.immediat),tarifAConfirmer:aConfirmer,motifsTarif:motifs,adresseAVerifier:motifs.includes("adresse"),multiVehicules:motifs.includes("groupe")},client:{nom,telephone:tel},langue:["fr","en"].includes(texte(bon.langue,2))?texte(bon.langue,2):"fr",conditionsAcceptees:{version:texte(bon.conditionsAcceptees?.version,20),langue:["fr","en"].includes(texte(bon.conditionsAcceptees?.langue,2))?texte(bon.conditionsAcceptees?.langue,2):"fr"},provenance:texte(bon.provenance,120),provenanceCle,parReception:receptionAutorisee,paiement,paiementNom:texte(bon.paiementNom,60),contact:contactPropre(bon.contact),prix:{total:prixDepose,ht:Math.round((prixDepose/1.10)*100)/100,tva:Math.round((prixDepose-prixDepose/1.10)*100)/100,majoration:false,serveurVerifie:false}};
 const empreinteDepot=await sha256(JSON.stringify(propre));propre.cree=new Date().toISOString();propre.securite={empreinteDepot,prixServeurVerifie:false,provenanceServeurVerifie:false};
 /* LE QUOTA D'UNE RÉCEPTION IDENTIFIÉE EST LE SIEN, PAS CELUI DU WIFI (2 octobre 2026). Douze dépôts par heure et par adresse IP : à l'hôtel, la tablette du comptoir et les clients sur le wifi partagent souvent la même adresse — un jour d'affluence, le treizième client voyait « votre demande n'a pas pu nous être transmise ». Une réception dont la session est vérifiée compte sur sa propre clé, avec un plafond à sa mesure ; les visiteurs anonymes gardent le plafond par adresse. */
 const ip=(req.headers.get("cf-connecting-ip")||req.headers.get("x-forwarded-for")||"inconnue").split(",")[0].trim(),heureQuota=new Date().toISOString().slice(0,13);
 /* LES CLIENTS DU QR SUR LE WIFI DE L'HÔTEL (3 octobre 2026, choix de Barbaros). Ils ne sont pas la réception — pas de session — mais ils partagent eux aussi l'adresse de la box de l'hôtel : treize clients en une heure, et le treizième lisait « non transmise » sans que personne ne soit alerté. Une demande qui porte la clé d'un partenaire RÉEL — lue dans la table partenaires, jamais crue sur parole : une clé inventée donnerait sinon un compteur neuf par clé — compte sur sa propre clé « hôtel + adresse + heure », plafonnée à 30. Le plafond anonyme ordinaire reste à 12 : un attaquant qui connaît la clé de l'hôtel (elle est dans les liens du QR) gagne 30 au lieu de 12, rien de plus. Si la table ne répond pas, on retombe sur le plafond ordinaire plutôt que de refuser. */
 let hotelConnu=false;
 if(!receptionAutorisee&&/^[a-z0-9-]{3,40}$/.test(provenanceCle)){try{const p=await apiJson(`partenaires?cle=eq.${encodeURIComponent(provenanceCle)}&actif=eq.true&select=id&limit=1`);hotelConnu=!!p?.[0]?.id;}catch(_e){hotelConnu=false;}}
 const cleQuota=receptionAutorisee?await sha256("reception|"+provenanceCle+"|"+heureQuota):hotelConnu?await sha256("hotel|"+provenanceCle+"|"+ip+"|"+heureQuota):await sha256(ip+"|"+heureQuota),limiteQuota=receptionAutorisee?60:hotelConnu?30:12;
 const quota=await fetch(`${SUPABASE_URL}/rest/v1/rpc/consommer_quota_reservation`,{method:"POST",headers:{apikey:SERVICE_ROLE,Authorization:`Bearer ${SERVICE_ROLE}`,"Content-Type":"application/json"},body:JSON.stringify({p_cle:cleQuota,p_limite:limiteQuota})});if(!quota.ok)return reponse(503,{erreur:"service indisponible"},origin);if((await quota.json())!==true)return reponse(429,{erreur:"trop de demandes"},origin);
 const deja=await fetch(`${SUPABASE_URL}/rest/v1/courses?ref=eq.${encodeURIComponent(ref)}&select=bon&limit=1`,{headers:{apikey:SERVICE_ROLE,Authorization:`Bearer ${SERVICE_ROLE}`}});if(!deja.ok)return reponse(503,{erreur:"service indisponible"},origin);const lignes=await deja.json();if(Array.isArray(lignes)&&lignes.length){if(lignes[0]?.bon?.securite?.empreinteDepot===empreinteDepot)return reponse(200,{ok:true,ref,rejoue:true,...numeroDe(lignes[0])},origin);return reponse(409,{erreur:"référence déjà utilisée"},origin)}
 const snapshot=aConfirmer?null:await snapshotPartenaire(propre);if(!snapshot&&!aConfirmer)await controlerPrixKm(propre);const ins=await fetch(`${SUPABASE_URL}/rest/v1/rpc/ela_deposer_course_serveur`,{method:"POST",headers:{apikey:SERVICE_ROLE,Authorization:`Bearer ${SERVICE_ROLE}`,"Content-Type":"application/json"},body:JSON.stringify({p_ref:ref,p_bon:propre,p_snapshot:snapshot})});if(ins.status===409)return reponse(409,{erreur:"référence déjà utilisée"},origin);if(!ins.ok)return reponse(503,{erreur:"service indisponible"},origin);const num=await lireNumero(ref);return reponse(201,{ok:true,ref,tarifServeurVerifie:!!snapshot,...num},origin);
});
