import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")??"",S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const ORIGINES=new Set(["https://elatransfer.com","https://www.elatransfer.com"]);
const cors=(origin:string)=>({"Access-Control-Allow-Origin":ORIGINES.has(origin)?origin:"https://elatransfer.com","Access-Control-Allow-Headers":"apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"});
const reponse=(b:unknown,status:number,origin:string)=>new Response(JSON.stringify(b),{status,headers:{...cors(origin),"Content-Type":"application/json"}});
function texte(v:unknown,n:number){return String(v??"").trim().slice(0,n)}
function propre(o:unknown,cles:string[]){const x=(o&&typeof o==="object"?o:{}) as Record<string,unknown>,r:Record<string,unknown>={};for(const k of cles)if(x[k]!==undefined)r[k]=x[k];return r}
async function db(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set("apikey",S);h.set("Authorization",`Bearer ${S}`);if(init.body)h.set("Content-Type","application/json");return fetch(`${U}/rest/v1/${path}`,{...init,headers:h});}
async function json(path:string){const r=await db(path);if(!r.ok)throw new Error(`db_${r.status}`);return r.json();}
function destinationValide(validation:any,course:any){if(!validation||validation.verification_manuelle)return false;const terminal=texte(course.terminal,80).toLowerCase(),trajet=(texte(course.departPublic||course.depart,300)+" "+texte(course.arriveePublic||course.arrivee,300)).toLowerCase();if(validation.terminal_prefix)return terminal.startsWith(String(validation.terminal_prefix).toLowerCase());if(validation.texte_contient)return trajet.includes(String(validation.texte_contient).toLowerCase());return false;}
async function snapshotPartenaire(safe:any){const partenaireCle=texte(safe.provenanceCle,80),destinationCle=texte(safe.course?.destinationCle,40).toLowerCase(),vehiculeCle=texte(safe.course?.vehiculeCle,30).toLowerCase();if(!partenaireCle||!destinationCle||!vehiculeCle)return null;try{const ps=await json(`partenaires?cle=eq.${encodeURIComponent(partenaireCle)}&actif=eq.true&select=id&limit=1`);if(!ps?.[0]?.id)return null;const fs=await json(`tarifs_partenaires?partenaire_id=eq.${encodeURIComponent(ps[0].id)}&destination_cle=eq.${encodeURIComponent(destinationCle)}&vehicule_cle=eq.${encodeURIComponent(vehiculeCle)}&actif=eq.true&select=montant_centimes,validation&limit=1`),f=fs?.[0];if(!f||!destinationValide(f.validation,safe.course))return null;const cs=await json('parametres_commerciaux?cle=eq.commission_ela_defaut&select=valeur&limit=1'),pct=Number(cs?.[0]?.valeur?.pourcentage);if(!Number.isFinite(pct)||pct<0||pct>100)return null;const prix=Number(f.montant_centimes);if(!Number.isInteger(prix)||prix<50)return null;const chauffeur=Math.round(prix*(1-pct/100));safe.prix={...(safe.prix||{}),total:prix/100};safe.securite={...(safe.securite||{}),prixServeurVerifie:true,sourceTarif:'partenaire'};return{prix_final_centimes:prix,montant_chauffeur_centimes:chauffeur,marge_ela_centimes:prix-chauffeur,destination_cle:destinationCle};}catch(e){console.warn('tarification partenaire non verrouillée',String(e));return null;}}
Deno.serve(async req=>{
 const origin=req.headers.get("origin")??"";
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});
 if(req.method!=="POST")return reponse({erreur:"methode"},405,origin);
 if(origin&&!ORIGINES.has(origin))return reponse({erreur:"origine"},403,origin);
 let x:any;try{x=await req.json()}catch{return reponse({erreur:"json"},400,origin)}
 const b=x?.bon;if(!b||typeof b!=="object")return reponse({erreur:"bon"},400,origin);
 const ref=texte(b.ref,32);if(!/^ELA-[A-Z0-9-]{6,24}$/i.test(ref))return reponse({erreur:"reference"},400,origin);
 const c=propre(b.course,["type","depart","arrivee","departPublic","arriveePublic","date","heure","terminal","vol","note","chambre","vehicule","vehiculeCle","passagers","distanceKm","destinationCle","estimee"]),cl=propre(b.client,["nom","telephone"]),prix=propre(b.prix,["total","ht","tva","majoration"]);
 c.depart=texte(c.depart,300);c.arrivee=texte(c.arrivee,300);c.departPublic=texte(c.departPublic,300);c.arriveePublic=texte(c.arriveePublic,300);c.date=texte(c.date,10);c.heure=texte(c.heure,5);c.terminal=texte(c.terminal,80);c.vol=texte(c.vol,30);c.note=texte(c.note,500);c.chambre=texte(c.chambre,30);c.vehicule=texte(c.vehicule,60);c.vehiculeCle=texte(c.vehiculeCle,30);c.passagers=texte(c.passagers,60);c.destinationCle=texte(c.destinationCle,40);
 cl.nom=texte(cl.nom,120);cl.telephone=texte(cl.telephone,30);if(!cl.telephone||!c.date||!c.heure)return reponse({erreur:"champs"},400,origin);
 const safe:any={ref,statut:"attente",cree:new Date().toISOString(),course:c,client:cl,prix,paiement:texte(b.paiement,30),paiementNom:texte(b.paiementNom,60),langue:texte(b.langue,5),provenance:texte(b.provenance,100),provenanceCle:texte(b.provenanceCle,80),parReception:!!b.parReception,pancarte:!!b.pancarte,securite:{source:"passerelle-publique-v2",prixServeurVerifie:false}};
 const depuis=new Date(Date.now()-60000).toISOString(),q=await db(`courses?select=ref,cree&cree=gte.${encodeURIComponent(depuis)}&limit=100`);if(q.ok){const a=await q.json(),meme=a.some((r:any)=>r.ref===ref);if(meme)return reponse({ok:true,ref,duplique:true},200,origin);if(a.length>=60)return reponse({erreur:"quota"},429,origin)}
 const snapshot=await snapshotPartenaire(safe),r=await db('rpc/ela_deposer_course_serveur',{method:"POST",body:JSON.stringify({p_ref:ref,p_bon:safe,p_snapshot:snapshot})});
 if(!r.ok){const t=await r.text();if(r.status===409||t.includes('duplicate key'))return reponse({ok:true,ref,duplique:true},200,origin);return reponse({erreur:"depot"},502,origin)}
 return reponse({ok:true,ref,tarifServeurVerifie:!!snapshot},200,origin);
});
