import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")??"", S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"", STRIPE=Deno.env.get("STRIPE_SECRET_KEY")??"";
const ORIGINS=new Set(["https://elatransfer.com","https://www.elatransfer.com"]);
function j(status:number,body:Record<string,unknown>,origin=""){const h:Record<string,string>={"Content-Type":"application/json","Cache-Control":"no-store","Vary":"Origin"};if(ORIGINS.has(origin))h["Access-Control-Allow-Origin"]=origin;return new Response(JSON.stringify(body),{status,headers:h});}
function t(v:unknown,n:number){return typeof v==="string"?v.trim().slice(0,n):"";}
async function db(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set("apikey",S);h.set("Authorization",`Bearer ${S}`);if(init.body)h.set("Content-Type","application/json");return fetch(`${U}/rest/v1/${path}`,{...init,headers:h});}
Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin")??"";if(req.method==="OPTIONS"){if(!ORIGINS.has(origin))return j(403,{erreur:"refusé"});return new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":origin,"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"content-type, apikey","Vary":"Origin"}});}if(req.method!=="POST"||!ORIGINS.has(origin))return j(403,{erreur:"refusé"});if(!U||!S||!STRIPE||!STRIPE.startsWith("sk_test_"))return j(503,{erreur:"paiement_test_indisponible"},origin);
let x:any;try{x=await req.json();}catch{return j(400,{erreur:"requête invalide"},origin);}const ref=t(x?.ref,32),tel=t(x?.telephone,40);if(!/^ELA-[A-Z0-9-]{6,24}$/.test(ref)||tel.length<6)return j(400,{erreur:"demande invalide"},origin);
const cr=await db(`courses?ref=eq.${encodeURIComponent(ref)}&select=bon&limit=1`);if(!cr.ok)return j(503,{erreur:"service indisponible"},origin);const courses=await cr.json();if(!courses?.length||t(courses[0]?.bon?.client?.telephone,40)!==tel)return j(404,{erreur:"réservation introuvable"},origin);
const sr=await db(`snapshots_financiers?course_ref=eq.${encodeURIComponent(ref)}&select=*&limit=1`);if(!sr.ok)return j(503,{erreur:"service indisponible"},origin);const snaps=await sr.json();const snap=snaps?.[0];if(!snap||snap.verifie!==true||snap.verrouille!==true||!Number.isInteger(snap.prix_final_centimes)||snap.prix_final_centimes<50)return j(409,{erreur:"tarif_non_verifie"},origin);
const pr=await db(`paiements?course_ref=eq.${encodeURIComponent(ref)}&select=*&limit=1`);if(!pr.ok)return j(503,{erreur:"service indisponible"},origin);const ps=await pr.json();let intent:any=null;if(ps?.[0]?.stripe_payment_intent_id){const r=await fetch(`https://api.stripe.com/v1/payment_intents/${encodeURIComponent(ps[0].stripe_payment_intent_id)}`,{headers:{Authorization:`Bearer ${STRIPE}`}});if(r.ok)intent=await r.json();}
if(!intent||["canceled","succeeded"].includes(intent.status)){const form=new URLSearchParams();form.set("amount",String(snap.prix_final_centimes));form.set("currency","eur");form.set("capture_method","manual");form.set("automatic_payment_methods[enabled]","true");form.set("metadata[course_ref]",ref);const r=await fetch("https://api.stripe.com/v1/payment_intents",{method:"POST",headers:{Authorization:`Bearer ${STRIPE}`,"Content-Type":"application/x-www-form-urlencoded","Idempotency-Key":`ela-test-${ref}-${snap.cree_le}`},body:form});intent=await r.json();if(!r.ok)return j(502,{erreur:"stripe_creation_echouee"},origin);}
const row={course_ref:ref,stripe_payment_intent_id:intent.id,mode:"test",statut:intent.status==="requires_capture"?"autorise":intent.status,montant_autorise_centimes:intent.amount_capturable||0,montant_capture_centimes:intent.amount_received||0,modifie_le:new Date().toISOString()};const wr=await db("paiements?on_conflict=course_ref",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(row)});if(!wr.ok)return j(503,{erreur:"etat_paiement_non_enregistre"},origin);return j(200,{ok:true,client_secret:intent.client_secret,statut:intent.status,mode:"test"},origin);});
